In [1]:
import pandas as pd
import numpy as np

In [2]:
import numpy as nb
data0 = [2,4,6.5,8]
arr0 = np.array(data0)


In [3]:
#任务2pandas中的Series数据类型
s = pd.Series(data=[100,'a',{'dic1': 5 }],
              index=pd.Index(['id1',20,'third'],name='my_idx'),
              dtype='object',
              name='my_name')

In [4]:
s2 = pd.Series(["1","2","3","4"])

In [5]:
s2.index.values

array([0, 1, 2, 3], dtype=int64)

In [6]:
type(s2.values[0])

str

In [7]:
s2.shape

(4,)

In [8]:
s2.size

4

In [9]:
#任务1：将列表转化为Numpy数组
import numpy as np
list_data = [1,2,3,4,5]
array_data = np.array(list_data)
print(array_data)

[1 2 3 4 5]


In [13]:
#任务2

In [11]:
#任务3
d = {
    "one": pd.Series([1.0,2.0,3.0],index=["a","b","c"]),
    "two": pd.Series([1.0,2.0,3.0,4.0],index=["a","b","c","d"]),
}
df = pd.DataFrame(d)

In [20]:
d1 = {
     "作者":pd.Series(['余华','残血','莫言']),
     "作品":pd.Series(['活着','暗夜','红高粱']),
    "价格":pd.Series([32,45,56]),
}
df2 = pd.DataFrame(d1)

In [21]:
df2.index.values

array([0, 1, 2], dtype=int64)

In [22]:
df2.size

9

In [23]:
df2.shape

(3, 3)

In [24]:
df2['价格']

0    32
1    45
2    56
Name: 价格, dtype: int64

In [25]:
df2['作品']

0     活着
1     暗夜
2    红高粱
Name: 作品, dtype: object

In [26]:
df2['作者']

0    余华
1    残血
2    莫言
Name: 作者, dtype: object